name: "Notify PR Open in Slack"
description: "Notify action for send slacks messages about when a PR is open or closed."
inputs:
  CHANNEL_ID: 
    description: "Channel ID"
  BOT_TOKEN_GITHUB:
    description: "Slack bot token"
  TEAM_NAME:
    description: "Slack bot token"
  GITHUB_TOKEN:
    description: "Github token generated"

outputs:
  GITHUB_MERGED_TITLE:
    description: "Github merged title"
    value: ${{ steps.github_merged_title.outputs.github_merged_title }}
  GITHUB_MERGED_URL:
    description: "Github merged URL"
    value: ${{ steps.github_merged_url.outputs.github_merged_url }}
  GITHUB_AUTHOR:
    description: "Github author"
    value: ${{ steps.github_author.outputs.github_author }}
runs:
  using: "composite"
  steps:
    - name: Notify to Slack channel
      id: slack
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' && !github.event.pull_request.draft }}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.CHANNEL_ID}}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:pr_open: Review required @${{ inputs.TEAM_NAME}} by ${{ github.event.pull_request.user.login }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:pencil: ${{ github.event.pull_request.title }}*"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Review here",
                    "emoji": true
                  },
                  "value": "review_here",
                  "url": "${{ github.event.pull_request.html_url }}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.BOT_TOKEN_GITHUB}}
    
    - uses: actions/checkout@v3
    - name: Get merged title
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
      id: github_merged_title
      run: |
        if git log -n 1 --pretty=format:"%s" ${{ github.sha }} | grep -q "/"; then
          github_merged_title=$(git log -n 1 --pretty=format:"%s" ${{ github.sha }} | cut -d' ' -f5- | xargs basename -s '/' | tail -1)
        else
          github_merged_title=$(git log -n 1 --pretty=format:"%s" ${{ github.sha }})
        fi
        echo "github_merged_title=$github_merged_title" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Author
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
      id: github_author
      run: |
        github_author=$(git log --format="%an" -n 1 ${{ github.sha }})
        echo "github_author=$github_author" >> $GITHUB_OUTPUT
      shell: bash
    - name: Get merged url
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
      id: github_merged_url
      run: |
        github_merged_url=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/pulls\?state\=closed | jq -r '.[0].html_url'| xargs printf "%s/files\n")
        echo "github_merged_url=$github_merged_url" >> $GITHUB_OUTPUT
      shell: bash


    - name: Notify to Slack channel
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.CHANNEL_ID}}
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:merged: ${{ steps.github_merged_title.outputs.github_merged_title }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:bust_in_silhouette: ${{ steps.github_author.outputs.github_author }}*"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "See more",
                    "emoji": true
                  },
                  "value": "See more",
                  "url": "${{ steps.github_merged_url.outputs.github_merged_url }}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.BOT_TOKEN_GITHUB}}
