name: "Notify PR Open & Push to Main Branches in Slack"
description: "Notifies on Slack when a PR is opened (non-draft) or when code is pushed to develop, staging, or main branches."

inputs:
  CHANNEL_ID:
    description: "Slack Channel ID where notifications will be sent."
    required: true
  SLACK_BOT_TOKEN: # Rename of BOT_TOKEN_GITHUB 
    description: "Slack Bot Token with permissions to post messages."
    required: true
  TEAM_NAME:
    description: "Optional Slack team/group handle (@team-name) to mention on new PRs."
    required: false
  GITHUB_TOKEN:
    description: "GitHub Token needed to interact with the GitHub API (e.g., fetch PR details)."
    required: true

runs:
  using: "composite"
  steps:
    - name: Notify PR Opened to Slack
      id: slack_pr_opened
      # Only if PR is not draft
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' && !github.event.pull_request.draft }}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.CHANNEL_ID }}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:pr_open: Review required${{ inputs.TEAM_NAME && format(' @{0}', inputs.TEAM_NAME) || '' }} by ${{ github.event.pull_request.user.login }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:pencil: ${{ github.event.pull_request.title }}*"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Review here",
                    "emoji": true
                  },
                  "url": "${{ github.event.pull_request.html_url }}",
                  "action_id": "button-review-pr"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}


    - name: Checkout code
      id: checkout_code
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Get Commit Info
      id: get_commit_info
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
      run: |
        commit_title=$(git log -n 1 --pretty=format:"%s" ${{ github.sha }})
        commit_author=$(git log -n 1 --pretty=format:"%an" ${{ github.sha }})
        echo "commit_title=$commit_title" >> $GITHUB_OUTPUT
        echo "commit_author=$commit_author" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Associated PR Info
      id: get_pr_info
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
      run: |
        PR_INFO_JSON=$(curl -sfL \
          -H "Accept: application/vnd.github.groot-preview+json" \
          -H "Authorization: Bearer ${{ inputs.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls")

        PR_URL=$(echo "$PR_INFO_JSON" | jq -r '.[0].html_url // empty')

        if [[ -z "$PR_URL" ]]; then
          echo "No associated PR found for commit ${{ github.sha }}"
          PR_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
        else
           PR_URL="${PR_URL}/files"
        fi

        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
      shell: bash

    - name: Notify Push/Merge to Slack
      id: slack_push_notify
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main') }}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.CHANNEL_ID }}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:merged: Merged to ${{ github.ref_name }}:* ${{ steps.get_commit_info.outputs.commit_title }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:bust_in_silhouette: By:* ${{ steps.get_commit_info.outputs.commit_author }}"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "See Changes",
                    "emoji": true
                  },
                  # Usa la URL del PR encontrado (o la del commit si no se encontró PR)
                  "url": "${{ steps.get_pr_info.outputs.pr_url }}",
                  "action_id": "button-see-changes"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}